### ISSUE TITLE
ConcurrentLinkedQueue issues with scala native

### ISSUE THREAD

**Issue by alterationx10** [com-lihaoyi/os-lib#117]
I have a project where I'm trying to use os-lib 0.8.1 (and scala native 0.4.7). If I try to run my code, even with os-lib just in the imports, I will get:

```
[error] Found 5 missing definitions while linking
[error] Not found Member(Top(java.util.concurrent.ConcurrentLinkedQueue),D3addL16java.lang.ObjectzEO)
[error]         at /home/runner/work/zio/zio/core/shared/src/main/scala/zio/internal/FiberRuntime.scala:1253
[error] Not found Member(Top(java.util.concurrent.ConcurrentLinkedQueue),D4pollL16java.lang.ObjectEO)
[error]         at /home/runner/work/zio/zio/core/shared/src/main/scala/zio/internal/FiberRuntime.scala:223
[error] Not found Member(Top(java.util.concurrent.ConcurrentLinkedQueue),D5offerL16java.lang.ObjectzEO)
[error]         at /home/runner/work/zio/zio/core/shared/src/main/scala/zio/internal/impls/LinkedQueue.scala:46
[error] Not found Member(Top(java.util.concurrent.ConcurrentLinkedQueue),D6addAllL20java.util.CollectionzEO)
[error]         at /home/runner/work/zio/zio/core/shared/src/main/scala/zio/internal/impls/LinkedQueue.scala:53
[error] Not found Member(Top(java.util.concurrent.ConcurrentLinkedQueue),D7isEmptyzEO)
[error]         at /home/runner/work/zio/zio/core/shared/src/main/scala/zio/internal/FiberRuntime.scala:222
```

That ZIO source code above calls > `private val queue   = new java.util.concurrent.ConcurrentLinkedQueue[FiberMessage]()`

I see that there is an implementation of ConcurrentLinkedQueue in os-lib, but there is also a version supplied by scala-native. 

https://github.com/scala-native/scala-native/blob/main/javalib/src/main/scala/java/util/concurrent/ConcurrentLinkedQueue.scala

I was able to build a local version with the os-lib implementation removed, and using that, my project worked just fine. Could to os-lib one be safely removed from the project?

**Comment by lefou** [comment]
Fixed by #122
