### ISSUE TITLE
Version 0.8.1 is missing from release notes in readme

### ISSUE THREAD

**Issue by SethTisue** [com-lihaoyi/os-lib#123]
also, the version number wasn't bumped in the Getting Started section

**Comment by SethTisue** [comment]
personally, if this was my project I would write `"<version>"` in the readme and let the user insert the current version — the current GitHub web UI does a good job of highlighting the current version number

I personally would also not bother with the changelog in the readme and let https://github.com/com-lihaoyi/os-lib/releases serve as the change log of record

**Comment by lefou** [comment]
Thanks for reporting, @SethTisue.

About the changelog: I really appreciate projects that maintain a changelog rather than letting the user decipher what various commit messages and/or pull request titles mean.

@jodersky do you mind to update the Readme accordingly. Asking you, as you tagged that release. If you can't, no problem, I can do it then later.

**Comment by SethTisue** [comment]
> letting the user decipher what various commit messages and/or pull request titles

(as you wish, but I don't think letting the GitHub release notes serve as the changelog means that the quality has to be low. I offer scala/scala as an example: we aggressively rename PRs and edit their descriptions exactly for that reason, as well as putting a lot of work into organizing and editing the release notes so they aren't just a hail of bullets)

**Comment by SethTisue** [comment]
as you wish. but the question of quality seems orthogonal to me to whether the log lives in the readme or lives in the GitHub release notes

**Comment by lefou** [comment]
> (as you wish. but the question of quality seems orthogonal to me to the question of whether the log lives in the readme or lives in the GitHub release notes)

Personally, I always favor changelog inside files (e.g. `Readme.adoc` or `Changelog.txt`) in the repo. They are locally available in ever checkout, can be searched ofline, can be shipped in the JAR, whereas Notes attached to GitHub Release Page is GitHub-only and online. I've migrated too many project between too many platform, I guess.

For the Readme format I think it's a good idea to migrate to AsciiDoctor. It accepts almost all Markdown syntax, is rendered on GitHub as well as Markdown and supports variables and TOCs out of the box.

**Comment by SethTisue** [comment]
thanks :-)

**Comment by jodersky** [comment]
@lefou, thanks for taking care of it!
