### ISSUE TITLE
os.remove() returns Boolean not Unit

### ISSUE THREAD

**Issue by ShaanHash** [com-lihaoyi/os-lib#133]
As per the documentation the...

`os.remove()`  method returns `Boolean` and not `Unit`

The readme.md should be changed to reflect the actual implementation.

**Comment by lefou** [comment]
Can you please point to the concrete lines, where `Boolean` is used? I just looked right now, and it looks correct to me.

**Comment by ShaanHash** [comment]
In ReadMe.Adoc we list this method signature as:

`os.remove(target: Path): Unit`

However in practice this method returns `Boolean`

Line 283 in FileOps.scala

`object remove extends Function1[Path, Boolean]`

**Comment by lefou** [comment]
Ah, now I see. Last time I checked `os.remove.all` which is defined as the Readme says:  `object all extends Function1[Path, Unit]`. But you're right, `os.remove` returns indeed `Boolean`.

Thanks for the pointer. Do you want to submit a pull request with the changes, by any chance?
