### ISSUE TITLE
[feature request] zip file handling (500USD Bounty)

### ISSUE THREAD

**Issue by robmwalsh** [com-lihaoyi/os-lib#161]
---

**From the maintainer Li Haoyi**: I'm putting a 500USD bounty on this issue, payable by bank transfer on a merged PR implementing this.

Success criteria is a design and implementation of zip file handling in OS-Lib: zipping, unzipping, listing-without-unzipping, usage as a filesystem so you can generate `os.Path`s to read and write inside the zip without unzipping, etc. Along with tests exercising the logic, updated documentation, and documented limitations (e.g. not all filesystem operations can take place inside a zip file). This is to be done in the OS-Lib style, with default parameters, nested objects with apply methods as necessary, and exception-based error handling.

---

I'm loving all the filesystem handling stuff, particularly `walk`ing the file system, but it all falls down when I hit a zip file (actually a jar in this case, but whatevs). The only remotely friendly way I've found to deal with zip files in scala is [better-files](https://github.com/pathikrit/better-files#zip-apis). At the moment I've just pulled in the dep for handling the jars, but it'd be awesome to have support for zip files baked into os-lib, particularly the ability to walk into jars and copy files to jars as easily as os-lib makes these operations on regular files/folders.

**Comment by lihaoyi** [comment]
I've also come across this need

**Comment by chaitanyawaikar** [comment]
@lefou Do we have a discord channel where we can discuss the approach ?

**Comment by lihaoyi** [comment]
@chaitanyawaikar can use the com-lihaoyi discord https://discord.com/channels/632150470000902164/940067748103487558

**Comment by chaitanyawaikar** [comment]
> lihaoyi

Could you please send an invite link please ? The above link does not lead me to any channel

**Comment by chaitanyawaikar** [comment]
Hello @lihaoyi 
I am raising the following [PR](https://github.com/com-lihaoyi/os-lib/pull/316) to address this issue. I look forward to receiving your valuable feedback.
