### ISSUE TITLE
Add optional root in Path and support for roots for Windows

### ISSUE THREAD

**Issue by szymon-rd** [com-lihaoyi/os-lib#170]
Per the following discussion: https://github.com/com-lihaoyi/os-lib/discussions/136
I propose that we: 
 * Introduce a getter for optional root in `Path`
 * Return the `root` in `segments`. Java's `Path` returns segments without the drive letter, but keeps the information. I.e. - the path is relative, root is not present, and the .getRoot on segments return null, but the segments can be brought back to be absolute with `.toAbsolutePath`. `segments` in os-lib do something different that Java's Path iterator, as it returns only Strings, not relative paths that can be made absolute.
 * TBD: Add `RootPath` class to expose `apply` accepting a drive letter. It could be the type of `os.root`, so people could do either `os.root / ...` or `os.root("C:") / ...`. We could also add `os.drive("C:")` or something like that, and leave the `os.root` defaulting to the system drive.

**Comment by lihaoyi** [comment]
I think it sounds reasonable

**Comment by lihaoyi** [comment]
We do a similar thing with `os.resource`, which can be called as `os.resource(foo)` to pass in an explicit classloader

**Comment by lefou** [comment]
We definitely need some test coverage and documentation for the edge cases, e.g. making a path relative to another fails when the root is not the same.

**Comment by lihaoyi** [comment]
Do we have to return `root` in `segments`? what if we just don't? 

Anyone who wants it can call `.root`, and anyone who wants the equivalent Java paths can call `.toIO`/ `.toNIO`. I don't think being able to reconstruct the `os.Path` purely from its `segments` is a hard requirement

**Comment by lefou** [comment]
Now, we claim that there should be no need to use lower level Java API, which isn't fully true unless we cover Windows file system roots. But there is a reason, why Unix-like OSes don't have the "drive" distinction. It sucks. I think, we should not include the root in the segments, but handle it properly in (de-)serialization.

**Comment by lefou** [comment]
Maybe, we can just invent some new type to deal with full Windows paths including a drive letter and provide some way to resolve it from a `os.Path` or vice versa.

**Comment by lihaoyi** [comment]
I wonder if https://github.com/com-lihaoyi/os-lib/issues/167 is related to this issue? JVM on linux cna have multiple filesystem roots too IIRC, with ZipFileSystems and in memory file systems, so it's not purely a windows-ism. Presumably whatever we do for Windows should work for those as wel

**Comment by szymon-rd** [comment]
> Maybe, we can just invent some new type to deal with full Windows paths including a drive letter and provide some way to resolve it from a `os.Path` or vice versa.

One could argue that root on Unix-like OSes is just `/`, and on windows `C:\`. That gives somewhat consistent behavior.

**Comment by lefou** [comment]
> JVM on linux cna have multiple filesystem roots too IIRC, with ZipFileSystems and in-process virtual file systems, so it's not purely a windows-ism. Presumably whatever we do for Windows should work for those as well

Do we target these use cases? Do we have a way in os-lib API to select a files system?

**Comment by lihaoyi** [comment]
> Do we target these use cases? Do we have a way in os-lib API to select a files system?

I've never thought about it, but if we're aiming for OS-Lib to be a feature-complete wrapper of the `java.io`/`java.nio` filesystem APIs, then being able to operate across filesystem roots does seem to make sense. That means Windows drives, ZipFileSystem, in-memory JimFS, etc.

And I think it shouldn't be too much complexity either. I think once we get the `os.Path`s able to support different filesystem roots, then everything else should mostly just work since `os.*` mostly just forwards to `java.io`/`java.nio` underneath.
