### ISSUE TITLE
Add % and %% from ammonite-ops

### ISSUE THREAD

**Issue by phdoerfler** [com-lihaoyi/os-lib#175]
I was using ammonite-ops for writing short scala shell scripts in the past and grew quite fond of `%` and `%%`.
Please consider adding them to os-lib, thanks!

I find myself adding them to some of my scripts that use os-lib:
```scala
def %(args: os.Shellable*) =
  os.proc(args:_*).call(stderr = os.Inherit, stdin = os.Inherit, stdout = os.Inherit)
def %%(args: os.Shellable*) =
  os.proc(args:_*).call(stderr = os.Inherit, stdin = os.Inherit)
```

**Comment by lihaoyi** [comment]
Probably not going to happen, the whole point of moving to os-lib was to move away from such operator shorthands. You can continue using your own aliases where necessary
