### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by ysthakur** [com-lihaoyi/os-lib#179]
I don't know if scaladocs for OS-Lib already exist but I wasn't able to find them so I'm assuming they don't. Apologies if they already do and this issue is unnecessary.

I know OS-Lib is a small library and pretty much everything's documented in the Readme, but it'd still be nice to have API docs. If the maintainers think that's something worth having, I'd be happy to submit a PR (using GitHub Pages).

**Comment by SethTisue** [comment]
maybe just add an appropriate https://javadoc.io link to the readme? I think it's become less common for projects to publish Scaladoc/Javadoc themselves, since javadoc.io does such a good job with it
