### ISSUE TITLE
Add utility for more concise piping

### ISSUE THREAD

**Issue by szymon-rd** [com-lihaoyi/os-lib#187]
Right now, the only way to express a piping chain is something like this:
```scala
val curl = os.proc("curl", "-L" , "https://git.io/fpfTs").spawn(stderr = os.Inherit)
val gzip = os.proc("gzip", "-n").spawn(stdin = curl.stdout)
val sha = os.proc("shasum", "-a", "256").spawn(stdin = gzip.stdout)
```
I suggest that we could create additional API members that would allow expressing piping via a construct similar to the following one:
```scala
os.proc("curl", "-L" , "https://git.io/fpfTs")
   .pipeTo(os.proc("gzip", "-n"))
   .pipeTo(os.proc("shasum", "-a", "256"))
   .spawn(stderr = os.Inherit)
``` 
It could require introducing a new type, for example, a`ProcessGroup`.

**Comment by lihaoyi** [comment]
This seems reasonable. Piping things together linearly is enough of a common case that it could use some special syntax, perhaps with some flags for the common use cases (e.g. pipe stdout, pipe stderr, pipe both, etc.). And it makes sense to think of the entire process pipeline as a single thing that you can `.call` or `.spawn` rather than a bag of loose `os.Subprocess` objects

And If anyone wants a fancier set up they can always fall back to the more verbose set up above.

**Comment by szymon-rd** [comment]
What's more, it's also lacking some features / may behave counterintuitively, for example:
```scala
//> using toolkit latest
//> using scala 3.3
import java.util.concurrent.atomic.AtomicInteger

@main
def foo = 
    val a = os.proc("yes").spawn()
    val b = os.proc("head", "-n", "10").spawn(stdin = a.stdout)
    val c = os.proc("yes", "no").spawn(stdin = b.stdout)
    Thread.sleep(3000)
    println(c.isAlive())
    println(a.isAlive())
```
Thread run at ProcessInput.processInput for `yes` proc will fail with BrokenPipe, but the processes won't stop and will keep running.

**Comment by szymon-rd** [comment]
Generally, the pattern with a pipe constructed between the current process and the spawned one, and then a thread that handles forwarding the data to another process, is not optimal. It'd be much better just to do it like the real piping, then the correct process would get SIGPIPE and handle it properly - using yes and then head should not throw error, `yes` is capable of handling SIGPIPE. 
However, the only way I've found to do that is the `ProcessBuilder.startPipeline`. Sadly, it's available only from Java 9, so that would prohibit users with older versions from using os-lib.

**Comment by lihaoyi** [comment]
Could we make that functionality Java 9+ only? So people on Java 8 could use OSLib but without pipes, and people on 9+ could use OSLib with pipes, kind of mirroring the limitations of the underlying APi

It might also be possible to emulate the functionality in userland, but if it's too troublesome it might not be worth it.
