### ISSUE TITLE
os.proc on Scala Native

### ISSUE THREAD

**Issue by szymon-rd** [com-lihaoyi/os-lib#197]
Add support for working with processes for Scala Native. It seems to be blocked by lack of support for Threads on Native. Let's wait for native 0.5.x, it's planned for this year and will bring the Threads support.

**Comment by sequencer** [comment]
Seem scala-native/scala-native#3242 is already landed?
Any plan for os-lib to support `os.proc`? This might be the last piece to bring scala native become useful.

**Comment by lefou** [comment]
Haoyi already started something: https://github.com/com-lihaoyi/os-lib/pull/257

**Comment by lihaoyi** [comment]
This is done
