### ISSUE TITLE
Bug:  os.write.append doesn't append in Scala Native

### ISSUE THREAD

**Issue by leonbur** [com-lihaoyi/os-lib#205]
It's clearly overwriting existing text in the file. This works ok in JVM but Native has a bug. You can reproduce it with the example from the docs, or just copy paste this:

```
//> using toolkit latest
val wd = os.pwd

@main def main(args: String*): Unit =
    os.write.append(wd / "File.txt", "I am cow, hear me moo")
    println(os.read(wd / "File.txt")) //==> "I am cow, hear me moo"

    os.write.append(wd / "File.txt", ",\nI weigh twice as much as you")
    println(os.read(wd / "File.txt")) //==> ",\nI weigh twice as much as you" - but should have the "I am cow text" before it
```

Note, I'm using scala-cli with the latest toolkit directive.

**Comment by lihaoyi** [comment]
This seems to be fixed in the latest main branch, presumably from recent bugfixes in scalanative
