### ISSUE TITLE
Links in toc in README don't work

### ISSUE THREAD

**Issue by szymon-rd** [com-lihaoyi/os-lib#220]
Addresses in ToC at the beginning of README do not correspond to the sections in the document. For example, `os.read` in toc points to `os-read` section, but the actual name of the section is `osread`.

**Comment by lefou** [comment]
Could be that something has changed in Github. We need to investigate and play with AsciiDoc rendering and attributes, I guess.

**Comment by sake92** [comment]
GitHub now shows a menu on the top left, when you start scrolling.  
So this manually written TOC is a bit redundant IMHO.

**Comment by lefou** [comment]
This TOC is not manually written! It's automatically generated while rendering the AsciiDoc. It's one of _the_ features of AsciiDoc, that makes it so perfect for GitHub Readmes. I think GitHub somehow broke it's AsciiDoc rendering.
