### ISSUE TITLE
os.proc() sometimes returns error 143

### ISSUE THREAD

**Issue by olofwalker** [com-lihaoyi/os-lib#29]
OSLib: 1.4.2
Scala: 2.13
SBT: 1.2.8

I've been using the following way of spawning a child process and I see intermittent 143 / 137 errors. The application handles these errors and keeps running.

```
os.proc(commandLine()).call(timeout = 60)
```

I'm also trying out ZeroTurnarouns `zt-exec` where things seem to be consistently working.

**Comment by lihaoyi** [comment]
143/137 appears to be OS signal/OOMkill issues
