### ISSUE TITLE
Allow implicit conversions from `String => os.*Path` to allow multiple segments if the string is a literal (500USD Bounty)

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/os-lib#294]
---

**From the maintainer Li Haoyi**: I'm putting a 500USD bounty on this issue, payable by bank transfer on a merged PR implementing this.

---

Currently, `os.pwd / "foo/bar/baz"` fails. We do this to guard against people accidentally doing `os.pwd / myStringValue` and accidentally getting path traversal problems and such, and for people to explicitly say `os.pwd / os.SubPath(myStringValue)` or `os.pwd / os.RelPath(myStringValue)`. 

But if the RHS of the `/` is a literal string, there is no risk, and we should allow people to say `os.pwd / "foo/bar/baz"` instead of the more verbose `os.pwd / "foo" / "bar" / "baz"`. This can be done by making the implicit conversion from `String` to `SubPath`/`RelPath` a macro that checks whether the RHS is a literal, and if so goes through a different code path that allows it to contain multiple segments automatically

**Comment by pawelsadlo** [comment]
I will take a look

**Comment by pawelsadlo** [comment]
@lihaoyi I think it might be possible to do by utilizing scala.ValueOf, and Singleton upper bound, do you require it to be implemented with macro?

**Comment by lihaoyi** [comment]
@pawelsadlo I'd be ok with non-macro implementations. The main requirement is that it only work for literal strings and that it give some kind of useful error message when used on non-literal strings
