### ISSUE TITLE
JVM exception when trying to use os-lib in almond Jupiter notebook

### ISSUE THREAD

**Issue by melton1968** [com-lihaoyi/os-lib#33]
I am getting a jvm exception when trying to do basic operations with the os-lib library. The code runs fine in a local scala repl, but not in my online notebook or my own local  installation. I am at a loss of how to proceed.

I know this might not be anything to do with os-lib, but I figured you might be able to point me in a direction because I rely heavily on this library.

```
import $ivy.`com.lihaoyi::os-lib:0.6.2`
os.Path("/abc") / "def"

```

```
Downloading https://repo1.maven.org/maven2/com/lihaoyi/os-lib_2.12/0.6.2/os-lib_2.12-0.6.2.pom
Downloaded https://repo1.maven.org/maven2/com/lihaoyi/os-lib_2.12/0.6.2/os-lib_2.12-0.6.2.pom
Downloading https://repo1.maven.org/maven2/com/lihaoyi/geny_2.12/0.4.2/geny_2.12-0.4.2.pom
Downloaded https://repo1.maven.org/maven2/com/lihaoyi/geny_2.12/0.4.2/geny_2.12-0.4.2.pom
Downloading https://repo1.maven.org/maven2/com/lihaoyi/os-lib_2.12/0.6.2/os-lib_2.12-0.6.2.jar
Downloading https://repo1.maven.org/maven2/com/lihaoyi/os-lib_2.12/0.6.2/os-lib_2.12-0.6.2-sources.jar
Downloading https://repo1.maven.org/maven2/com/lihaoyi/geny_2.12/0.4.2/geny_2.12-0.4.2.jar
Downloading https://repo1.maven.org/maven2/com/lihaoyi/geny_2.12/0.4.2/geny_2.12-0.4.2-sources.jar
Downloaded https://repo1.maven.org/maven2/com/lihaoyi/geny_2.12/0.4.2/geny_2.12-0.4.2-sources.jar
Downloaded https://repo1.maven.org/maven2/com/lihaoyi/geny_2.12/0.4.2/geny_2.12-0.4.2.jar
Downloaded https://repo1.maven.org/maven2/com/lihaoyi/os-lib_2.12/0.6.2/os-lib_2.12-0.6.2-sources.jar
Downloaded https://repo1.maven.org/maven2/com/lihaoyi/os-lib_2.12/0.6.2/os-lib_2.12-0.6.2.jar
java.lang.NoSuchMethodError: os.Path.$div(Los/PathChunk;)Los/Path;
  ammonite.$sess.cmd0$Helper.<init>(cmd0.sc:2)
  ammonite.$sess.cmd0$.<init>(cmd0.sc:7)
  ammonite.$sess.cmd0$.<clinit>(cmd0.sc:-1)
```

In a local REPL>

Welcome to Scala 2.12.10 (OpenJDK 64-Bit Server VM, Java 1.8.0_232).
Type in expressions for evaluation. Or try :help.

```
scala> val p = os.Path("/abc")
 
p: os.Path = /abc

scala> val p2 = p / "def"
p2: p.ThisType = /abc/def

scala> 
```

**Comment by melton1968** [comment]
I've narrowed this down to the following: I have a library that uses os-lib internally and when I import that library in a Jupyter notebook using almond, the ammonite.ops that is use by almond somehow interferes with my libraries internal use of os-lib.

My current work around is to clone os-lib and repackage as oslib (instead of os) and use that in my library internally and then everything is happy. Is there an alternative?

**Comment by ongzexuan** [comment]
Which library was specifically that was interfering? I am facing the same issue. I am using requests, ujson, os-lib at the moment.

**Comment by Krever** [comment]
I propose to close this issue as it has its copy in almond repo, which is directly responsible for classpath mismatch (https://github.com/almond-sh/almond/issues/518)
