### ISSUE TITLE
Non-equality of PathChunk makes mock-testing difficult

### ISSUE THREAD

**Issue by skestle** [com-lihaoyi/os-lib#41]
I'm trying to assert that certain files don't get loaded unnecessarily in my software so have attempted to mock a Path (scalatest with IdiomaticMockito):
```
val mockFolder = mock[Path]
mockFolder / "should-be-read" returns realFolder / "should-be-read"
mockFolder / "should-not-be-read" throws <an exception indicating why it shouldn't be read>
```
Unfortunately, it seems that because Strings are implicitly converted to `PathChunk` by the `/` method, and `PathChunk` does not implement equality, then when the real code calls `mockFolder / "should-be-read"`, the "should-be-read" parameter is not the same as the one registered in the mock.

I'll work around and comment, but this is a bit disappointing.

**Comment by skestle** [comment]
To workaround, I imported `ArgumentMatchersSugar` (mockito) and updated code to
```
mockFolder / argMatching { case chunk: PathChunk => chunk.segments.head == "should-be-read" } returns realFolder / "should-be-read"
mockFolder / * throws <detailed exception>
```

(Thankfully, my test only needs 1 file out of 2 so it's quite simple to modify to workaround)

**Comment by lihaoyi** [comment]
Going to call this a wontfix. `PathChunk` is an implementation detail to give us a nice syntax, and `Path` itself is a dumb data structure you should not need to mock. You can reorganize the code on your side if you want to assert these things, but we can't provide official support for mockito or similar on the os-lib side
