### ISSUE TITLE
Make the README more readable

### ISSUE THREAD

**Issue by MrPowers** [com-lihaoyi/os-lib#62]
Thanks for creating this great project and for putting all the docs in the README.  It's so much better having the public interface documented in a single file than an external website.

Here's how we might be able to make the README examples more readable.

Here's a snippet from the current README:

```scala
os.list(wd / "folder1") ==> Seq(wd / "folder1" / "one.txt")
os.move.into(wd / "File.txt", wd / "folder1")
os.list(wd / "folder1") ==> Seq(wd / "folder1" / "File.txt", wd / "folder1" / "one.txt")
```

We could phrase it like this instead.

Here's how to move the `wd/File.txt` file to the `wd/folder1/` directory.

```scala
os.move.into(wd / "File.txt", wd / "folder1")
```

Run `os.list(wd / "folder1")` to confirm that it now contains `File.txt`.  The filesystem now looks like this:

```
wd/
  folder1/
    File1.txt
```

It's possible this wording will be easier to understand.  Like I said, the README is great as is and this refactoring is just a nice to have.

**Comment by lihaoyi-databricks** [comment]
Probably going to leave it as is
