### ISSUE TITLE
Releases missing from Maven central repository?

### ISSUE THREAD

**Issue by msugar** [com-lihaoyi/os-lib#72]
https://repo1.maven.org/maven2/com/lihaoyi/os-lib_2.11/ shows the latest release is 0.7.4. Before that, the latest one is 0.2.9. Shouldn't the releases between those two versions be available, too? 

The following page refers to version 0.7.1, which is not in Maven central anymore:
https://mungingdata.com/scala/filesystem-paths-move-copy-list-delete-folders/
That could cause some confusion.

Lots of things seemed to have changed since 0.2.9. Please, what are the official releases?

**Comment by lefou** [comment]
AFAIK, Scala 2.11 support was removed, but later re-added.

**Comment by msugar** [comment]
So it's 7.0.4 the latest good release we can use with Scala 2.11?

**Comment by lefou** [comment]
Yeah, up till now `0.7.4` is the latest and best release for Scala 2.11.
