### ISSUE TITLE
`proc.call` and `.spawn` incorrectly throw `java.io.IOException`

### ISSUE THREAD

**Issue by jackkoenig** [com-lihaoyi/os-lib#82]
scala: 2.13.6
ammonite: 2.4.0
os-lib: 0.7.2 (via ammonite)

`proc.call(check = false)` is supposed to "avoid throwing an exception if the subprocess fails with a non-zero exit code" [[1]](https://github.com/com-lihaoyi/os-lib#osproccall). However, it seems that `java.io.IOException` is thrown unconditionally:

```
$ amm
Loading...
Welcome to the Ammonite Repl 2.4.0 (Scala 2.13.6 Java 11.0.11)
@ os.proc("foo").call(check = false) 
java.io.IOException: Cannot run program "foo" (in directory ".../oslib"): error=2, No such file or directory
  java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
  java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
  os.proc.proc$lzycompute$1(ProcessOps.scala:128)
  os.proc.proc$1(ProcessOps.scala:122)
  os.proc.spawn(ProcessOps.scala:135)
  os.proc.call(ProcessOps.scala:76)
  ammonite.$sess.cmd0$.<clinit>(cmd0.sc:1)
java.io.IOException: error=2, No such file or directory
...
```

Looking at that stack trace and the surrounding code, it looks like `proc.call` should **never** throw an `IOException` (https://github.com/com-lihaoyi/os-lib/blob/790b81aba491047b73dd481e290abb36ee1a7de8/os/src-jvm/ProcessOps.scala#L85) so I think this the `SubProcess` logic in `os.proc.spawn` is not properly suppressing the Java `IOException`: https://github.com/com-lihaoyi/os-lib/blob/790b81aba491047b73dd481e290abb36ee1a7de8/os/src-jvm/ProcessOps.scala#L122

**Comment by jodersky** [comment]
I think that this behaves as expected. As you mentioned, the `check = false` flag should avoid throwing an exception if the subprocess exits with a non-zero exit code. However, if the process cannot be spawned in the first place, then there is no choice but to throw (or we would need change the function signature of `call` and `spawn` to return some kind of option type).

See the results of these interactive tests:
```
scala> os.proc("false").call() // false returns 1, so this should throw
os.SubprocessException: CommandResult 1

  at os.SubprocessException$.apply(Model.scala:202)
  at os.proc.call(ProcessOps.scala:85)
  ... 28 elided

scala> os.proc("false").call(check = false) // error is suppressed                                                                                                                                                                                                      
val res4: os.CommandResult = CommandResult 1

scala> os.proc("nonexistant").call(check = false) // we still get an error, because "nonexistant" is does not exist                                                                                                                                                                                                    
java.io.IOException: Cannot run program "nonexistant" (in directory "/home/jodersky/p/buildsio"): error=2, No such file or directory
  at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1141)
  at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1072)
  at os.proc.proc$lzyINIT1$7(ProcessOps.scala:128)
  at os.proc.proc$1(ProcessOps.scala:133)
  at os.proc.spawn(ProcessOps.scala:135)
  at os.proc.call(ProcessOps.scala:76)
  ... 28 elided
Caused by: java.io.IOException: error=2, No such file or directory
  at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
  at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
  at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
  at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1108)
  ... 33 more
```

Maybe another way to look at spawning is to consider the semantics of a raw `exec` vs spawning a process from a shell such as bash. In case the executable doesn't exist, `exec` fails and sets an error code. The shell on the other hand will signal the failure by returning a synthetic exit code typically 127.
