### ISSUE TITLE
resolving any path 

### ISSUE THREAD

**Issue by syspulse** [com-lihaoyi/os-lib#84]
I feel rather stupid not finding an easy solution for somethins like this: 
```
os.AnyPath("/tmp/file.log")
os.AnyPath("./log/file.log")
os.AnyPath("../log/file.log") 
```
Is there a universal path resolver ?

**Comment by alexarchambault** [comment]
That's what `os.FilePath` is for I believe. And then you can call `resolveFrom` on it to get an `os.Path`.

**Comment by lefou** [comment]
You're probably looking for `os.Path.apply`.

https://github.com/com-lihaoyi/os-lib/blob/master/os/src/Path.scala#L380

It accepts an `PathConvertible`, e.g. a `String` and a base directory, which is used in case the given path is relative, to make it absolute.

**Comment by alexarchambault** [comment]
That's `os.write(os.Path(fileName, os.pwd), data)` then (that's what @lefou suggested I believe).

**Comment by syspulse** [comment]
@alexarchambault Thanks!
